# Generated by Django 5.2.12 on 2026-10-07 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('age_years', models.DecimalField(decimal_places=2, max_digits=6)),
                ('kind', models.CharField(choices=[('walk_in', 'Walk-in'), ('appointment', 'Appointment')], max_length=12)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('referring_doctor', models.CharField(blank=True, max_length=160)),
                ('clinical_history', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clinic.patient')),
            ],
            options={
                'ordering': ['-scheduled_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='booked', max_length=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clinic.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_requests', to='clinic.bookingitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(choices=[('collection', 'Collection'), ('refund', 'Refund'), ('reversal', 'Correction reversal')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('card', 'Card'), ('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='clinic.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='clinic.moneytransaction')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('disease_group', models.CharField(blank=True, max_length=160)),
                ('fields', models.JSONField(default=list)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service')),
            ],
            options={
                'ordering': ['service__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('template_snapshot', models.JSONField(default=dict)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('values', models.JSONField(default=dict)),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('diagnosis_snapshot', models.JSONField(default=list)),
                ('finalized', models.BooleanField(default=False)),
                ('revision_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('diagnoses', models.ManyToManyField(to='clinic.diagnosis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='clinic.bookingitem')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revision', to='clinic.reportversion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.reporttemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveIntegerField()),
                ('prefix', models.CharField(max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='clinic.bookingitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service')),
            ],
            options={
                'ordering': ['date', 'service_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='TokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.UniqueConstraint(fields=('booking', 'service'), name='one_service_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 0), ('price__gte', 0), ('discount__lte', models.F('price'))), name='valid_booked_price'),
        ),
        migrations.AddConstraint(
            model_name='moneytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='unique_report_version'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'number'), name='unique_daily_token'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('item',), name='one_active_token_per_item'),
        ),
        migrations.AddConstraint(
            model_name='tokencounter',
            constraint=models.UniqueConstraint(fields=('service', 'date'), name='one_daily_counter'),
        ),
    ]
