# Generated by Django 5.2.12 on 2026-10-07 12:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models



def seed_legacy_clinic(apps, schema_editor):
    Organization = apps.get_model('clinic', 'Organization')
    Clinic = apps.get_model('clinic', 'Clinic')
    Organization.objects.using(schema_editor.connection.alias).create(id=1, name='Sajjad Healthcare Organisation')
    Clinic.objects.using(schema_editor.connection.alias).create(id=1, organization_id=1,
        name='Sajjad Poly Clinic and Diagnostic Center', code='SPC',
        doctor_name='Dr. Asfa Batool', qualifications='FCPS Radiology, MBBS')


def fill_patient_ids(apps, schema_editor):
    Patient = apps.get_model('clinic', 'Patient')
    for patient in Patient.objects.using(schema_editor.connection.alias).all().iterator():
        patient.global_id = uuid.uuid4()
        patient.save(update_fields=['global_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinic', '0002_diagnosis_booking_bookingitem_discountrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9-]{1,15}$', 'Use 2–16 uppercase letters, digits or hyphens.')])),
                ('address', models.TextField(blank=True, max_length=1000)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('doctor_name', models.CharField(blank=True, max_length=160)),
                ('qualifications', models.CharField(blank=True, max_length=160)),
                ('prescription_footer', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OPDVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('chief_complaint', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('examination', models.TextField()),
                ('vitals', models.JSONField(default=dict)),
                ('diagnosis_snapshot', models.JSONField(default=list)),
                ('medicines', models.JSONField(default=list)),
                ('advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('revision_reason', models.CharField(blank=True, max_length=500)),
                ('patient_snapshot', models.JSONField(default=dict)),
                ('clinic_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_id', models.UUIDField(unique=True)),
                ('canonical_id', models.UUIDField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=12)),
                ('global_id', models.UUIDField()),
                ('patient_id', models.UUIDField()),
                ('version', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('patient', 'Patient'), ('visit', 'Visit')], max_length=12)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('acknowledged_version', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursor', models.PositiveBigIntegerField(default=0)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='clinic_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='global_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(fill_patient_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patient',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cnic',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'CNIC must contain 13 digits.')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='token_prefix',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]{0,7}$', 'Use 1–8 uppercase letters or digits, starting with a letter.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Organisation admin'), ('admin', 'Admin'), ('operator', 'Operator'), ('doctor', 'Doctor')], default='operator', max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.RunPython(seed_legacy_clinic, migrations.RunPython.noop),
        migrations.AddField(
            model_name='booking',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='patient',
            name='owner_clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('clinic', 'name'), name='unique_clinic_service_name'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('clinic', 'token_prefix'), name='unique_clinic_token_prefix'),
        ),
        migrations.AddField(
            model_name='opdversion',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opdversion',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opd_versions', to='clinic.booking'),
        ),
        migrations.AddField(
            model_name='opdversion',
            name='diagnoses',
            field=models.ManyToManyField(to='clinic.diagnosis'),
        ),
        migrations.AddField(
            model_name='opdversion',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.opdversion'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organisation_diagnosis'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'cnic'), name='unique_organisation_cnic'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'doctor')), fields=('clinic',), name='one_active_doctor_per_clinic'),
        ),
        migrations.AddField(
            model_name='patientalias',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientalias',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddField(
            model_name='remoterecord',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='remoterecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddField(
            model_name='syncclock',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clinic.organization'),
        ),
        migrations.AddField(
            model_name='synccredential',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='syncoutbox',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='syncstate',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clinic.clinic'),
        ),
        migrations.AddConstraint(
            model_name='opdversion',
            constraint=models.UniqueConstraint(fields=('booking', 'version'), name='unique_opd_version'),
        ),
        migrations.AddConstraint(
            model_name='remoterecord',
            constraint=models.UniqueConstraint(fields=('clinic', 'entity_type', 'global_id'), name='unique_remote_record'),
        ),
        migrations.AddConstraint(
            model_name='syncoutbox',
            constraint=models.UniqueConstraint(fields=('entity_type', 'entity_id'), name='unique_outbox_entity'),
        ),
    ]
