# Generated by Django 5.2.12 on 2026-10-07 13:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinic_opdversion_organization_patientalias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccredential',
            name='node_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncstate',
            name='node_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
