# Generated by Django 5.2.12 on 2026-10-07 13:15

from django.db import migrations, models


def classify_existing(apps, schema_editor):
    Service = apps.get_model('clinic', 'Service')
    Item = apps.get_model('clinic', 'BookingItem')
    for service in Service.objects.all():
        if 'consultation' in service.name.lower() or service.name.strip().lower() == 'opd':
            Service.objects.filter(pk=service.pk).update(category='opd')
            Item.objects.filter(service_id=service.pk).update(service_category='opd')


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_freeze_legacy_letterheads'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='service_category',
            field=models.CharField(default='imaging', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('imaging', 'Radiology / imaging'), ('opd', 'Doctor consultation / OPD')], default='imaging', max_length=10),
        ),
        migrations.RunPython(classify_existing, migrations.RunPython.noop),
    ]
