from django.urls import path
from . import views
from . import portal, branches

urlpatterns = [
    path('patients/directory/<uuid:global_id>/use/', branches.activate_patient, name='activate_patient'),
    path('patients/reconcile/', branches.reconcile_patients, name='reconcile_patients'),
    path('clinics/', branches.clinic_list, name='clinic_list'),
    path('clinics/new/', branches.clinic_edit, name='clinic_create'),
    path('clinics/<int:pk>/edit/', branches.clinic_edit, name='clinic_edit'),
    path('clinics/<int:pk>/configuration/', branches.branch_configuration, name='branch_configuration'),
    path('organization/reports/', branches.organization_report, name='organization_report'),
    path('synchronization/', branches.sync_status, name='sync_status'),
    path('sync/push/', branches.sync_push),
    path('sync/pull/', branches.sync_pull),
    path('bookings/<int:pk>/examine/', branches.opd_edit, name='opd_edit'),
    path('examinations/<int:pk>/', branches.opd_detail, name='opd_detail'),
    path('examinations/<int:pk>/print/', branches.opd_print, name='opd_print'),
    path('patients/<int:pk>/history/', branches.shared_history, name='shared_history'),
    path('', views.dashboard, name='dashboard'),
    path('patients/', views.patient_list, name='patient_list'),
    path('patients/new/', views.patient_edit, name='patient_create'),
    path('patients/<int:pk>/', views.patient_detail, name='patient_detail'),
    path('patients/<int:pk>/edit/', views.patient_edit, name='patient_edit'),
    path('services/', views.service_list, name='service_list'),
    path('services/new/', views.service_edit, name='service_create'),
    path('services/<int:pk>/edit/', views.service_edit, name='service_edit'),
    path('users/', views.staff_list, name='staff_list'),
    path('users/new/', views.staff_edit, name='staff_create'),
    path('users/<int:pk>/edit/', views.staff_edit, name='staff_edit'),
    path('audit/', views.audit_list, name='audit_list'),
    path('bookings/', portal.booking_list, name='booking_list'),
    path('bookings/new/', portal.booking_create, name='booking_create'),
    path('bookings/<int:pk>/', portal.booking_detail, name='booking_detail'),
    path('bookings/<int:pk>/reschedule/', portal.booking_reschedule, name='booking_reschedule'),
    path('bookings/<int:pk>/status/', portal.booking_status, name='booking_status'),
    path('bookings/<int:pk>/tokens/', portal.token_print, name='token_print'),
    path('queue/', portal.queue, name='queue'),
    path('items/<int:pk>/discount/', portal.discount_request, name='discount_request'),
    path('discounts/', portal.discount_list, name='discount_list'),
    path('discounts/<int:pk>/review/', portal.discount_review, name='discount_review'),
    path('bookings/<int:pk>/payment/', portal.payment_create, name='payment_create'),
    path('payments/<int:pk>/refund/', portal.payment_refund, name='payment_refund'),
    path('payments/<int:pk>/correct/', portal.payment_correct, name='payment_correct'),
    path('receipts/<int:pk>/', portal.receipt, name='receipt'),
    path('reports/cash/', portal.cash_report, name='cash_report'),
    path('reports/patients/', portal.patient_reports, name='patient_reports'),
    path('diagnoses/', portal.diagnosis_list, name='diagnosis_list'),
    path('diagnoses/new/', portal.diagnosis_edit, name='diagnosis_create'),
    path('diagnoses/<int:pk>/edit/', portal.diagnosis_edit, name='diagnosis_edit'),
    path('templates/', portal.template_list, name='template_list'),
    path('templates/new/', portal.template_edit, name='template_create'),
    path('templates/<int:pk>/edit/', portal.template_edit, name='template_edit'),
    path('items/<int:pk>/report/', portal.report_edit, name='report_edit'),
    path('clinical-reports/<int:pk>/', portal.report_detail, name='report_detail'),
    path('clinical-reports/<int:pk>/print/', portal.report_print, name='report_print'),
    path('backups/', portal.backup_page, name='backup_page'),
    path('backups/download/', portal.backup_download, name='backup_download'),
]
